# Default base image
ARG BASE_IMAGE=ubuntu:22.04

# To alter the base image, pass in a different image name to the build command:
#   docker build --build-arg BASE_IMAGE=ubuntu:20.04 .
FROM ${BASE_IMAGE}

ARG SNPE_ROOT=/opt/snpe1

###########################################################
## Copy and install Qualcomm® Neural Processing SDK (SNPE)
###########################################################
WORKDIR /opt
COPY downloads/snpe-1.68.0.zip .
RUN unzip /opt/snpe-1.68.0.zip \
    && rm snpe-1.68.0.zip \
    && mv snpe-1.68.0.3932 ${SNPE_ROOT}
ENV SNPE_ROOT=${SNPE_ROOT}
ENV PATH=$PATH:${SNPE_ROOT}/bin/x86_64-linux-clang/

# Set the working directory
WORKDIR /app
