# Default base image
ARG BASE_IMAGE=ubuntu:22.04

# To alter the base image, pass in a different image name to the build command:
#   docker build --build-arg BASE_IMAGE=ubuntu:20.04 .
FROM ${BASE_IMAGE}

# Install necessary dependencies

###########################################################
## Python Prerequistes Qualcomm® Neural Processing SDK (SNPE)
###########################################################
WORKDIR /opt
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y \
      python3.10 \
      python3-distutils \
      python3-pip \
      libpython3.10 \
    && python3.10 -m pip install --upgrade pip \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install \
      tensorflow==2.10.1 \
      onnx==1.12.0 \
      onnxruntime==1.17.1 \
      tflite==2.3.0 \
    && python3 -m pip install torch==1.13.1+cpu torchvision==0.14.1+cpu torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cpu \
    && pip cache purge \
    && rm -rf /root/.cache/pip

ENV TENSORFLOW_HOME=/usr/local/lib/python3.10/site-packages/tensorflow/core
ENV PATH=$PATH:/opt/snpe/b
ENV PYTHONPATH=$PYTHONPATH:$SNPE_ROOT/lib/python

# Set the working directory
WORKDIR /app

