# Default base image
ARG BASE_IMAGE=ubuntu:22.04

# To alter the base image, pass in a different image name to the build command:
#   docker build --build-arg BASE_IMAGE=ubuntu:20.04 .
FROM ${BASE_IMAGE}

###########################################################
## Prerequistes Qualcomm® Neural Processing SDK (SNPE)
###########################################################
WORKDIR /opt
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get remove -y \
      openjdk-11-jdk \
      default-jre \
    && apt-get install -y \
      unzip \
      git \
      wget \
      curl \
      make \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables for the Qualcomm® Neural Processing SDK (SNPE)
#   See /opt/hexagon_sdk/setup_sdk_env.source for details


# Set the working directory
WORKDIR /app
