# Default base image
ARG BASE_IMAGE=ubuntu:22.04

# To alter the base image, pass in a different image name to the build command:
#   docker build --build-arg BASE_IMAGE=ubuntu:20.04 .
FROM ${BASE_IMAGE}

#################################################################
## Python Prerequistes Qualcomm® Neural Processing SDK (SNPE)
#################################################################
WORKDIR /opt
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y software-properties-common \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get install -y \
      python3-pip \
    && apt -y autoremove \
    && apt-get install -y \
      python3.6 \
      python3.6-distutils \
      python3.6-venv \
      libpython3.6 \
    && apt-get install -y \
      protobuf-compiler \
      cmake \
    && python3.6 -m pip install --upgrade pip \
    && rm -rf /var/lib/apt/lists/*

RUN python3.6 -m pip install \
      numpy==1.16.6 \
      sphinx==2.2.1 \
      scipy==1.4.1 \
      matplotlib==3.0.3 \
      protobuf==3.9.2 \
      pyyaml==5.1 \
      scikit-image==0.15.0 \
      tensorflow==2.3 \
      tflite==2.3.0 \
      onnx==1.3.0 \
      onnxruntime==1.6.00 \
    && python3.6 -m pip install torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html \
    && pip cache purge \
    && rm -rf /root/.cache/pip
RUN rm /usr/bin/python3 \
  && ln -s /usr/bin/python3.6 /usr/bin/python3
ENV TENSORFLOW_HOME=/usr/local/lib/python3.6/site-packages/tensorflow/core
ENV PATH=$PATH:/opt/snpe/b
ENV PYTHONPATH=$PYTHONPATH:$SNPE_ROOT/lib/python

# Set the working directory
WORKDIR /app
